baseURL = 'https://buildingbruges.be/'
languageCode = 'en-us'
title = 'Building Bruges'
paginate = 10

[params]
description = 'Building a Developer Community in and Around Bruges'

[[menus.main]]
name   = "Home"
url    = "/"
weight = 1

[[menus.main]]
name   = "Events"
url    = "/events/"
weight = 2

[[menus.main]]
name   = "Conference"
url    = "/conference/"
weight = 3

[[menus.main]]
name   = "Newsletter"
url    = "/stay-informed/"
weight = 4

[[menus.main]]
name   = "About"
url    = "/about/"
weight = 5

[[menus.main]]
name   = "Code of Conduct"
url    = "/code-of-conduct/"
weight = 6

[[menus.main]]
name   = "Call for Papers"
url    = "/call-for-papers/"
weight = 7

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
